# Generated by Django 3.2.5 on 2021-11-20 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0004_auto_20211120_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stickynote',
            name='canvas',
        ),
    ]
