# Generated by Django 3.2.5 on 2021-11-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0006_stickynote_canvas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickynote',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stickynote',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stickynote',
            name='what',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='stickynote',
            name='who',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='stickynote',
            name='why',
            field=models.TextField(null=True),
        ),
    ]
