# Generated by Django 3.2.5 on 2021-11-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0007_auto_20211121_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvas',
            name='image',
            field=models.URLField(default='https://via.placeholder.com/300.jpg'),
            preserve_default=False,
        ),
    ]
