# Generated by Django 3.2.5 on 2021-11-27 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0009_alter_canvas_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvas',
            name='image',
            field=models.URLField(default='https://images.unsplash.com/photo-1626094309830-abbb0c99da4a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1332&q=80'),
        ),
    ]
